name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./docker
        run: npm install

      - name: Run lint
        working-directory: ./docker
        run: npm run lint

      - name: Run tests
        working-directory: ./docker
        run: npm test

      - name: Build Docker image
        working-directory: ./docker
        run: docker build -t dawood09/my-node-app:latest .

      - name: Zip artifact
        run: zip -r app-artifact.zip docker/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: app-artifact.zip