name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verify directory
        run: ls -la
        shell: bash

      - name: Install dependencies
        run: npm install
        shell: bash

      - name: Run lint
        run: npm run lint
        shell: bash

      - name: Run tests
        run: npm test
        shell: bash

      - name: Build Docker image
        run: docker build -t dawood09/my-node-app:latest .
        shell: bash

      - name: Zip artifact
        run: zip -r app-artifact.zip . -x ".git/*" ".github/*" "docker-compose/*" "node_modules/*"
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: app-artifact.zip